title: Site

tabs:
  home:
    label: RISD.GD
    icon: bolt
    columns:
      - width: 1/2
        sections:
          pages: 
            type: pages
            layout: cards
          # subpages:
          #   extends: sections/subpages

      - width: 1/2
        sections:
          notices:
            extends: sections/notices
            search: true
  fonts:
    label: Typeface
    icon: headline
    columns:
      - width: 1/2
        fields:
          info: 
            type: info
            text: |
              Uploading multiple fonts (for example, WOFF and WOFF2), will set each successive font as an fallback for older browsers. In general, OTFs are fine.
          fontname:
            label: Font name
            type: text
          regularfont:
            type: files
            label: Regular font
            multiple: false
            uploads:
              template: font
            accept:
              extension: [woff2, woff, otf, ttf, eot]

          italicfont:
            type: files
            label: Italic font
            multiple: false
            uploads:
              template: font
            accept:
              extension: [woff2, woff, otf, ttf, eot]

      - width: 1/2
        sections: 
          fontFiles:
            type: files
            label: Upload font files
            layout: list
            # extends: sections/files
            template: font
            accept:
              extension: [otf, ttf, woff2, woff]

